name: 'Setup'
description: 'Setup the environment for running a task'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.32.2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'pnpm'
    - name: Link Dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
    - name: Pull down Turbo cache
      uses: actions/cache@v3
      with:
        path: node_modules/.cache/turbo
        key: turbo-${{ runner.os }}-${{ github.run_id }}
        restore-keys: |
          turbo-${{ runner.os }}
