name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronized]
jobs:
  calc-hash:
    name: Calculate Hash
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.calculate-cache-key.outputs.result }}
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Hash pnpm-lock.yaml file
        id: calculate-cache-key
        run: |
          runner="${{ runner.os }}"
          lock_hash="${{ hashFiles('pnpm-lock.yaml') }}"
          result="node_modules_${runner}_${lock_hash}"
          echo "::set-output name=result::$result"
        shell: bash

  setup:
    name: Setup & Validate Working Cache
    runs-on: ubuntu-latest
    needs: calc-hash
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ needs.calc-hash.outputs.cache-key }}
      - name: Install Dependencies
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: pnpm install --frozen-lockfile

  lint:
    name: Lint
    needs: [calc-hash, setup]
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/actions/setup
        with:
          cache-key: ${{ needs.calc-hash.outputs.cache-key }}
      - name: Lint
        run: pnpm run lint

  build:
    name: Build
    needs: [calc-hash, setup]
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/actions/setup
        with:
          cache-key: ${{ needs.calc-hash.outputs.cache-key }}
      - name: Build
        run: pnpm run build
