name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronized]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      
      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test