name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronized]
jobs:
  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/actions/setup
      - name: Lint
        run: pnpm run lint

  build:
    name: Build
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/actions/setup
      - name: Build
        run: pnpm run build
