name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronized]
jobs:
  setup:
    name: Setup Working Cache
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: example-key

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/actions/setup
        with:
          cache-key: example-key
      - name: Lint
        run: pnpm run lint

  build:
    name: Build
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/actions/setup
        with:
          cache-key: example-key
      - name: Lint
        run: pnpm run build
